Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2020-11, with the labels that each got.

#1013 Update countries-state.php
  includes/countries-state.php
Labels: Ready to Merge

#1010 Conflict with acf image field
  includes/fields/class-field-image.php
Labels: QA Approved

#1009 Fix/ajax type cat not showing on edit
  includes/fields/class-field-post-taxonomy.php
Labels: QA Approved

#1007 fix: multiple file image cant select fixed #205
  assets/js/upload.js
Labels: QA Approved

#1002 fix: option label not working when & use. tooltip added. fixed #218
  admin/form-builder/assets/js/components/field-option-data/template.php
Labels: QA Approved

#1012 Fix/url field new window not working
  includes/fields/class-field-url.php
Labels: Needs Changes, QA Approved

#1004 Invalid subscription
  class/payment.php
Labels: QA Approved

#977 Update class-frontend-form-post.php role base condition
  includes/class-frontend-form-post.php
Labels: Needs Dev Review, needs-testing

#1016 Missing product cat
  includes/class-frontend-form-post.php
  includes/free/form-element.php
Labels: Needs Changes

#1003 Fix/tax rate not affecting
  assets/js/billing-address.js
  wpuf-functions.php
Labels: Needs Dev Review, QA Approved
