Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2021-05, with the labels that each got.

#1060 Enhancement: Instruction tooltip for showing custom field data on post
  admin/form-builder/assets/js/form-builder.js
  admin/form-builder/assets/less/form-builder.less
  assets/css/wpuf-form-builder.css
  assets/images/custom-fields/advance.png
  assets/images/custom-fields/settings.png
  assets/js/wpuf-form-builder.js
  package-lock.json
Labels: Dev Review Done, QA Approved

#1075 Fix/template override not working
  includes/class-dokan-integration.php
  includes/class-wc-vendors-integration.php
  includes/class-wcmp-integration.php
Labels: Needs Dev Review, QA Approved

#1081 Add Mauritian Rupee for currency
  wpuf-functions.php
Labels: Needs Dev Review, QA Approved

#1086 gmap required doesnt work when multiple maps are on same form
  assets/js/frontend-form.js
Labels: Needs Dev Review, QA Approved

#1093 Fix/multiple login reg issue fixes
  includes/free/class-login.php
Labels: Needs Dev Review, QA Approved

#1104 eid ul fitr promotion added
  admin/promotion.php
Labels: QA Approved

#1073 Enhance/form preview page created
  admin/form-builder/views/form-builder.php
  wpuf-functions.php
Labels: Needs Dev Review, QA Approved

#1090 profile id issue fixed
  lib/gateway/paypal.php
Labels: Needs Dev Review, QA Approved

#1092 Enhance/post type menu on account page
  admin/settings-options.php
  class/frontend-account.php
  templates/dashboard/posts.php
  wpuf-functions.php
Labels: Needs Dev Review, QA Approved

#1088 Popup has a chance to get off-focus with a few 3rd party themes due to lower z-index
  assets/vendor/sweetalert2/dist/sweetalert2.css
Labels: Needs Dev Review, QA Approved

#1098 multiple subscription email notification fixed
  class/subscription.php
Labels: Needs Dev Review, QA Approved

#1099 paypal trial not working due to initial trial price
  lib/gateway/paypal.php
Labels: Needs Dev Review, QA Approved

#1105 Add Trinidad and Tobago Dollar
  wpuf-functions.php
Labels: Needs Dev Review, QA Approved

#1107 timepicker conflict with dokan store open close time picker fixed #1097
  wpuf.php
Labels: Needs Dev Review, QA Approved

#1087 column inner field cloning not working fixed #1085
  admin/form-builder/assets/js/form-builder.js
  admin/form-builder/assets/js/mixins/add-form-field.js
Labels: Needs Dev Review, QA Approved
