Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2021-07, with the labels that each got.

#1124 existing account section filter improved for client modification
  class/frontend-account.php
  templates/dashboard/dashboard.php
  wpuf-functions.php
Labels: Needs Changes, QA Approved

#1135 Fix/file upload counter inconsistency
  assets/js/upload.js
  class/upload.php
Labels: Needs Dev Review, QA Approved

#1133 Remove unnecessary esc_html() from Login and Registration page template
  templates/login-form.php
  templates/registration-form.php
Labels: Dev Review Done, QA Approved

#1136 guest ppp not working fixed #1134
  class/payment.php
Labels: Needs Dev Review, QA Approved

#1142 date adjusted for summer promotion
  admin/promotion.php
Labels: QA Approved
