Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2021-02, with the labels that each got.

#1052 fix: drag and drop not working properly for new field
  admin/form-builder/assets/js/components/builder-stage/index.js
  admin/form-builder/assets/js/form-builder.js
  admin/form-builder/assets/js/mixins/add-form-field.js
Labels: Dev Review Done, QA Approved

#1061 menu position has chenged due to dokan has same menu position
  admin/class-admin-settings.php
Labels: Dev Review Done, QA Approved

#1041 Fix/ajax child of not working
  includes/fields/class-field-post-taxonomy.php
Labels: Dev Review Done, QA Approved

#1051 non recurring subscription did not work fixed using daily cron
  class/subscription.php
Labels: Dev Review Done, QA Approved

#1053 fix: address field not working when used with conditional logic
  wpuf-functions.php
Labels: Dev Review Done, QA Approved

#1057 Enhancement: Update registration form shortcode notice
  assets/css/admin.css
  includes/free/loader.php
Labels: QA Approved

#1062 Fix/post redirection to payment
  includes/class-frontend-form-post.php
Labels: Dev Review Done, QA Approved

#1068 Fix/email doesnt set as username
  includes/free/class-registration.php
Labels: Needs Dev Review, QA Approved

#1070 Fix/login redirect empty previous url
  includes/free/class-login.php
Labels: QA Approved

#1063 fix: meta key will not change if label update fixed #1050
  admin/form-builder/assets/js/form-builder.js
Labels: Dev Review Done, QA Approved
