Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2022-11, with the labels that each got.

#1275 [FREE] option ordering not working as expected fixed #1272
  admin/form-builder/assets/js/components/field-option-data/index.js
  assets/js/wpuf-form-builder-components.js
Labels: QA Approved, Ready to Merge, Dev Review Done

#1254 [FREE] email style handled
  wpuf-functions.php
Labels: QA Approved, Ready to Merge, Dev Review Done

#1299 [FREE] fix: textarea selection bug in field options
  admin/form-builder/assets/js/components/form-post_excerpt/template.php
  assets/js-templates/form-components.php
  class/post-form-templates/post.php
  includes/class-upgrades.php
  includes/fields/class-field-post-content.php
  includes/fields/class-field-post-excerpt.php
  includes/free/post-form-templates/the_events_calendar.php
  includes/free/post-form-templates/woocommerce.php
  includes/upgrades/upgrade-3.6.0.php
  languages/wp-user-frontend.pot
  wpuf.php
Labels: QA Approved, Ready to Merge

#1255 [PRO] Fix/conditional logic not working on metabox
  admin/posting.php
  includes/fields/class-abstract-fields.php
Labels: QA Approved, Ready to Merge, Dev Review Done

#1298 fix: update sweetalert2 version
  admin/form-builder/assets/js/components/builder-stage/index.js
  admin/form-builder/assets/js/components/form-column_field/index.js
  admin/form-builder/assets/js/components/form-fields/index.js
  admin/form-builder/assets/js/form-builder.js
  admin/form-builder/assets/js/mixins/add-form-field.js
  admin/form-builder/assets/js/mixins/global.js
  admin/form-builder/class-wpuf-admin-form-builder.php
  admin/posting.php
  assets/js/frontend-form.js
  assets/js/upload.js
  assets/js/wpuf-admin.js
  assets/js/wpuf-form-builder-components.js
  assets/js/wpuf-form-builder-mixins.js
  assets/js/wpuf-form-builder.js
  assets/vendor/sweetalert2/dist/sweetalert2.common.js
  assets/vendor/sweetalert2/dist/sweetalert2.css
  assets/vendor/sweetalert2/dist/sweetalert2.js
  assets/vendor/sweetalert2/dist/sweetalert2.min.css
  assets/vendor/sweetalert2/dist/sweetalert2.min.js
  class/admin-asset-loader.php
  class/asset-loader.php
  wpuf.php
Labels: Needs Dev Review, QA Approved, Ready to Merge

#1281 Button style updated for multistep forms
  assets/less/frontend-forms.less
Labels: Needs Dev Review, QA Approved, Ready to Merge

#1256 Fix: password strength validation added
  assets/js/frontend-form.js
  assets/less/frontend-forms.less
Labels: QA Approved, Ready to Merge

#1306 Fix/upgrade prompts design revamp
  admin/form-builder/assets/less/form-builder.less
  admin/form-template.php
  admin/html/modal.php
  admin/settings-options.php
  assets/css/admin.css
  assets/css/admin/wpuf-module.css
  assets/css/wpuf-form-builder.css
  assets/images/check.svg
  assets/images/conditional-form.png
  assets/images/content-restriction.png
  assets/images/crown.svg
  assets/images/diamond.svg
  assets/images/modules.png
  assets/images/profile-header-template-1.jpg
  assets/images/profile-header-template-2.jpg
  assets/images/profile-header-template-3.jpg
  assets/images/templates/edd.png
  assets/images/user-listing-template-1.jpg
  assets/images/user-listing-template-2.jpg
  assets/images/user-listing-template-3.jpg
  assets/images/user-listing-template-4.jpg
  assets/images/user-listing-template-5.jpg
  assets/images/user-listing-template-6.jpg
  assets/images/woocommerce-form-template.png
  assets/images/x.svg
  assets/js/admin/wpuf-module.js
  assets/js/wpuf-admin.js
  assets/less/admin.less
  assets/less/metabox-tabs.less
  assets/vendor/swiffy-slider/swiffy-slider-extensions.min.js
  assets/vendor/swiffy-slider/swiffy-slider.min.css
  assets/vendor/swiffy-slider/swiffy-slider.min.js
  includes/free/loader.php
  includes/free/post-form-templates/easy_digital_download.php
  includes/free/prompt.php
  includes/free/subscription.php
  lib/class.settings-api.php
  wpuf-functions.php
Labels: QA Approved, Ready to Merge

#1311 dropdown field ordering fixed for float number
  admin/form-builder/assets/js/components/field-option-data/index.js
  assets/js/wpuf-form-builder-components.js
Labels: QA Approved, Ready to Merge

#1289 [FREE] fix: frontend form validation
  assets/js/frontend-form.js
  includes/fields/class-field-checkbox.php
  includes/fields/class-field-radio.php
  includes/fields/class-field-textarea.php
  includes/fields/class-field-url.php
Labels: needs: dev review, QA Approved, Ready to Merge
