Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2022-03, with the labels that each got.

#1033 Payment instructions
  class/payment.php
  lib/class.settings-api.php
  lib/gateway/bank.php
  lib/gateway/paypal.php
Labels: QA Approved, Dev Review Done

#1221 fix: Datetime related wrapper function introduced
  wpuf-functions.php
Labels: Dev Review Done

#1234 fix: Content restriction not working
  assets/js/frontend-form.js
  includes/class-frontend-form-post.php
  includes/fields/class-field-textarea.php
Labels: QA Approved, Dev Review Done

#1239 fix: Validation for email and URL
  assets/js/frontend-form.js
Labels: Needs Dev Review, QA Approved

#1222 fix: Preview option added in user profile
  class/frontend-account.php
  templates/dashboard/posts.php
Labels: QA Approved, Dev Review Done

#1236 fix: New function parameter added
  wpuf-functions.php
Labels: needs-testing, Dev Review Done

#1247 fix: Reset password message requesting from AJAX
  assets/js/wpuf-login-widget.js
  includes/free/class-login.php
Labels: needs-testing, Needs Dev Review

#1245 Fix/add phone field in form builder
  admin/form-builder/assets/js/components/field-radio/template.php
  assets/js/frontend-form.js
Labels: Needs Dev Review, QA Approved
