Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2025-08, with the labels that each got.

#1665 Fix/modal open 3dot open and some design
  assets/css/admin/form-builder.css
  assets/css/admin/subscriptions.min.css
  assets/css/forms-list.min.css
  assets/js/components/FormsList.vue
  assets/js/forms-list.min.js
  assets/js/forms-list.min.js.map
  includes/Admin/template-parts/modal-v4.2.php
  includes/Admin/views/post-forms-list-table-view.php
Labels: QA Approved

#1667 Fix/icon social field
  admin/form-builder/assets/js/components/builder-stage-v4-1/template.php
  admin/form-builder/assets/js/components/builder-stage/template.php
  assets/js-templates/form-components.php
Labels: QA Approved, needs: developer feedback

#1673 Revert "form builder meta empty meta key which comes from empty level and dup…"
  admin/form-builder/assets/js/form-builder.js
  assets/js/wpuf-form-builder.js
Labels: QA Approved

#1675 Fix/radio button fix and ec template not showing
  admin/form-builder/assets/js/components/field-radio/template.php
  assets/js-templates/form-components.php
  includes/Admin/Forms/Post/Templates/Post_Form_Template_WooCommerce.php
Labels: QA Approved, Dev Review Done

#1685 feat(upload): allow webp image format in file upload fields
  includes/Fields/Form_Field_Featured_Image.php
  includes/Fields/Form_Field_Image.php
  wpuf-functions.php
Labels: needs: dev review, QA Approved

#1683 Remove form template option from post form builder
  wpuf-functions.php
Labels: QA Approved

#1682 fix: submit button conditional logic
  admin/form-builder/views/post-form-settings.php
  assets/js/forms-list.min.js
  assets/js/forms-list.min.js.map
  assets/js/subscriptions.min.js
  assets/js/subscriptions.min.js.map
  languages/wp-user-frontend.pot
  package-lock.json
  wpuf-functions.php
Labels: QA Approved
