Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2025-07, with the labels that each got.

#1611 fix: conflict with email log plugin
  assets/js/components/FormsList.vue
Labels: needs: dev review, QA Approved

#1609 Add integration support and improve selectize handling
  admin/form-builder/assets/js/form-builder.js
  assets/css/admin/form-builder.css
  assets/js/wpuf-form-builder.js
Labels: QA Approved

#1616 feat: Update country list and improve state handling
  includes/Data/countries.php
  wpuf-functions.php
Labels: needs: dev review

#1619 fix: PPP Cost is Empty and Saved in Post form Payment Settings
  admin/form-builder/assets/js/form-builder.js
  admin/html/form-settings-payment.php
  assets/js/wpuf-form-builder-wpuf-forms.js
  assets/js/wpuf-form-builder.js
  includes/Ajax/Admin_Form_Builder_Ajax.php
  wpuf-functions.php
Labels: needs: dev review, QA Approved

#1621 Feature/template filtering search in post form
  assets/css/admin.css
  assets/css/admin/form-builder.css
  assets/css/admin/subscriptions.min.css
  assets/css/forms-list.min.css
  assets/js/forms-list.min.js
  assets/js/forms-list.min.js.map
  assets/less/admin.less
  changelog.txt
  includes/Admin/Menu.php
  includes/Admin/template-parts/modal-v4.2.php
Labels: QA Approved, Dev Review Done

#1635 chore: paypal unnecessary log remove
  Lib/Gateway/Paypal.php
Labels: needs: dev review

#1639 fix: wpuf-post-forms-list-table-overflow-hidden
  includes/Admin/views/post-forms-list-table-view.php
Labels: needs: dev review

#1642 fix: conditionally show 'Require email verification'
  admin/form-builder/assets/js/form-builder.js
  assets/js/wpuf-form-builder.js
Labels: QA Approved, Dev Review Done

#1638 feat: facebook field implementation
  admin/form-builder/assets/js/components/builder-stage-v4-1/template.php
  admin/form-builder/assets/js/components/builder-stage/template.php
  assets/js-templates/form-components.php
Labels: QA Approved, Dev Review Done

#1650 Enhance/product tag searchable
  admin/form-builder/assets/js/components/field-select/index.js
  admin/form-builder/assets/js/components/form-taxonomy/index.js
  assets/js-templates/form-components.php
  assets/js/wpuf-form-builder-components.js
  includes/Fields/Form_Field_Post_Taxonomy.php
Labels: QA Approved, Dev Review Done
