Repository weDevsOfficial/wp-user-frontend, pull requests merged in 2025-05, with the labels that each got.

#1561 Fix: Render HTML tags in help text instead of displaying as plain text
  includes/Admin/views/support.php
Labels: QA Approved, Ready to Merge

#1564 arrow button style fix
  admin/form-builder/assets/js/components/builder-stage-v4-1/template.php
  admin/form-builder/assets/js/components/form-column_field/template.php
  assets/css/admin/form-builder.css
  assets/js-templates/form-components.php
Labels: QA Approved, Ready to Merge

#1566 fix: coupons functionality in frontend
  includes/Admin.php
Labels: needs: dev review

#1565 enhance: feature lock
  Lib/Gateway/Bank.php
  Lib/Gateway/Paypal.php
  admin/form-builder/assets/js/components/form-fields-v4-1/index.js
  assets/js/wpuf-form-builder-components.js
  includes/Admin.php
  includes/Admin/Forms/Field_Manager.php
  includes/Free/Free_Loader.php
  includes/Free/templates/page-registration-form.php
  includes/Frontend/Frontend_Account.php
  includes/functions/settings-options.php
  wpuf.php
Labels: QA Approved

#1562 Update: Revised Pay Per Post help text to reflect current functionality
  includes/Admin/views/support.php
Labels: QA Approved, Ready to Merge

#1558 fix: pro popup button color inconsistency
  assets/css/admin/form-builder.css
  assets/js/components/subscriptions/SectionInputField.vue
Labels: QA Approved

#1575 fix: REST API support for subdirectory calls
  assets/css/admin/subscriptions.min.css
  assets/css/forms-list.min.css
  assets/js/components/FormsList.vue
  assets/js/components/subscriptions/SubscriptionBox.vue
  assets/js/forms-list.min.js
  assets/js/forms-list.min.js.map
  assets/js/stores/subscription.js
  assets/js/subscriptions.min.js
  assets/js/subscriptions.min.js.map
  includes/Admin/Admin_Subscription.php
  languages/wp-user-frontend.pot
  readme.md
  readme.txt
Labels: QA Approved

#1576 Feat/paypal library upgrade
  Lib/Gateway/Paypal.php
  assets/images/wpuf_paypal.png
  phpcs.xml.dist
Labels: QA Approved, needs: developer feedback

#1579 fix: redirect error and message issues
  Lib/Gateway/Paypal.php
Labels: QA Approved
